/**
 * Client Token Generator
 * 
 * Generates a SHA-256 token based on the user's browser context (user agent).
 * This token cannot be generated by automated scripts (curl, Node.js, etc.)
 * because it requires access to the real browser's navigator.userAgent and
 * WebCrypto API.
 * 
 * The token is stored in localStorage and sent with sensitive API requests
 * to prevent automated attacks.
 */

import { sha256 } from '@noble/hashes/sha256';
import { utf8ToBytes } from '@noble/hashes/utils';

const LEGACY_CLIENT_TOKEN_KEY = 'clientToken';
const CLIENT_TOKEN_STATE_KEY = 'clientToken.state.v1';
const TOKEN_GENERATION_SECRET = process.env.NEXT_PUBLIC_CLIENT_TOKEN_SECRET || 'fry-rewards-client-';
const TOKEN_MAX_AGE_MS = 24 * 60 * 60 * 1000; // rotate daily to avoid stale bindings

type StoredClientToken = {
  token: string;
  userAgent: string;
  createdAt: number;
};

const getNavigatorUA = (): string => {
  if (typeof navigator === 'undefined') {
    return '';
  }
  return navigator.userAgent || '';
};

function readState(): StoredClientToken | null {
  if (typeof window === 'undefined') return null;
  try {
    const raw = window.localStorage.getItem(CLIENT_TOKEN_STATE_KEY);
    if (raw) {
      const parsed = JSON.parse(raw) as StoredClientToken;
      if (parsed?.token && parsed?.userAgent) {
        return parsed;
      }
    }
  } catch {
    // ignore parse/storage issues
  }

  // Fallback to legacy plain string storage so we can migrate seamlessly.
  try {
    const legacy = window.localStorage.getItem(LEGACY_CLIENT_TOKEN_KEY);
    if (legacy) {
      return {
        token: legacy,
        userAgent: '__legacy__',
        createdAt: 0
      };
    }
  } catch {
    // ignore
  }

  return null;
}

function persistState(state: StoredClientToken): void {
  if (typeof window === 'undefined') return;
  try {
    window.localStorage.setItem(
      CLIENT_TOKEN_STATE_KEY,
      JSON.stringify(state)
    );
    // Keep writing the legacy key so logged-in tabs that still expect it can read.
    window.localStorage.setItem(LEGACY_CLIENT_TOKEN_KEY, state.token);
  } catch {
    // ignore storage quota errors
  }
}

let inflightTokenPromise: Promise<string> | null = null;

/**
 * Generate a SHA-256 client token based on user agent.
 * This runs in the browser where navigator.userAgent is available.
 */
export async function generateClientToken(userAgentOverride?: string): Promise<string> {
  const userAgent = userAgentOverride ?? getNavigatorUA();
  if (!userAgent) {
    throw new Error('Token generation failed: missing user agent');
  }

  try {
    const payload = TOKEN_GENERATION_SECRET + userAgent;
    const encode = (input: string) => {
      if (typeof TextEncoder !== 'undefined') {
        return new TextEncoder().encode(input);
      }
      // Minimal fallback encoder to keep older mobile browsers working.
      return Uint8Array.from(unescape(encodeURIComponent(input)).split('').map((c) => c.charCodeAt(0)));
    };

    const subtle = typeof crypto !== 'undefined' ? crypto.subtle ?? (crypto as any).webkitSubtle : undefined;
    if (subtle && typeof subtle.digest === 'function') {
      // Preferred path: native WebCrypto for speed and security.
      const hashBuffer = await subtle.digest('SHA-256', encode(payload));
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      return hashArray.map((b) => b.toString(16).padStart(2, '0')).join('');
    }

    // Fallback: pure JS hash to support environments without WebCrypto (older mobile Safari / insecure contexts).
    const digest = sha256(utf8ToBytes(payload));
    return Array.from(digest).map((b) => b.toString(16).padStart(2, '0')).join('');
  } catch (err) {
    console.error('Failed to generate client token:', err);
    throw new Error('Token generation failed');
  }
}

/**
 * Get the stored client token from localStorage.
 * If not present, generate and store a new one.
 */
export async function getClientToken(options: { forceRefresh?: boolean } = {}): Promise<string> {
  if (typeof window === 'undefined') {
    console.warn('[ClientToken] getClientToken called on server');
    return '';
  }

  const forceRefresh = options.forceRefresh ?? false;
  if (inflightTokenPromise && !forceRefresh) {
    return inflightTokenPromise;
  }

  const rawPromise = (async () => {
    const userAgent = getNavigatorUA();
    if (!userAgent) {
      throw new Error('User agent unavailable');
    }

    const existing = readState();
    const now = Date.now();
    const age = existing ? now - existing.createdAt : Number.POSITIVE_INFINITY;
    const canReuseExisting =
      !forceRefresh &&
      existing?.token &&
      existing.userAgent === userAgent &&
      age < TOKEN_MAX_AGE_MS;

    if (canReuseExisting) {
      return existing.token;
    }

    const token = await generateClientToken(userAgent);
    persistState({ token, userAgent, createdAt: now });
    return token;
  })();

  const wrappedPromise = rawPromise
    .catch((error) => {
      const ua = getNavigatorUA();
      const hasLocalStorage = typeof window !== 'undefined' && !!window.localStorage;
      const state = typeof window !== 'undefined' ? readState() : null;
      const tokenAgeMs = state?.createdAt ? Date.now() - state.createdAt : null;
      console.error('[ClientToken] Failed to resolve token', error, {
        ua,
        hasLocalStorage,
        tokenAgeMs,
        hadStoredToken: Boolean(state?.token),
        forceRefresh
      });
      return '';
    })
    .finally(() => {
      if (inflightTokenPromise === wrappedPromise) {
        inflightTokenPromise = null;
      }
    });

  inflightTokenPromise = wrappedPromise;
  return wrappedPromise;
}

export async function refreshClientToken(): Promise<string> {
  clearClientToken();
  return getClientToken({ forceRefresh: true });
}

/**
 * Clear the stored token (useful for testing or logout)
 */
export function clearClientToken(): void {
  if (typeof window === 'undefined') return;
  try {
    window.localStorage.removeItem(LEGACY_CLIENT_TOKEN_KEY);
    window.localStorage.removeItem(CLIENT_TOKEN_STATE_KEY);
  } catch {
    // ignore
  }
}
