/**
 * Client Token Generator
 * 
 * Generates a SHA-256 token based on the user's browser context (user agent).
 * This token cannot be generated by automated scripts (curl, Node.js, etc.)
 * because it requires access to the real browser's navigator.userAgent and
 * WebCrypto API.
 * 
 * The token is stored in localStorage and sent with sensitive API requests
 * to prevent automated attacks.
 */

const CLIENT_TOKEN_KEY = 'clientToken';
const TOKEN_GENERATION_SECRET = 'fry-rewards-client-';

/**
 * Generate a SHA-256 client token based on user agent.
 * This runs in the browser where navigator.userAgent is available.
 */
export async function generateClientToken(): Promise<string> {
  try {
    // Combine secret + user agent
    const data = new TextEncoder().encode(TOKEN_GENERATION_SECRET + navigator.userAgent);
    
    // Use WebCrypto API (browser only, not available in Node.js scripts)
    const hashBuffer = await crypto.subtle.digest('SHA-256', data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    const token = hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
    
    return token;
  } catch (err) {
    console.error('Failed to generate client token:', err);
    throw new Error('Token generation failed');
  }
}

/**
 * Get the stored client token from localStorage.
 * If not present, generate and store a new one.
 */
export async function getClientToken(): Promise<string> {
  try {
    let token = localStorage.getItem(CLIENT_TOKEN_KEY);
    
    if (!token) {
      token = await generateClientToken();
      localStorage.setItem(CLIENT_TOKEN_KEY, token);
    }
    
    return token;
  } catch (err) {
    console.error('Failed to get client token:', err);
    return '';
  }
}

/**
 * Clear the stored token (useful for testing or logout)
 */
export function clearClientToken(): void {
  localStorage.removeItem(CLIENT_TOKEN_KEY);
}
