import type { MongoClient } from 'mongodb';

/**
 * RC1 (r12, 2026-09-22) — ownership proof for rebinding a device-wallet-clobbered
 * registration.
 *
 * The July premature binding (pre-F2 hardwareapi) bound installs to the device's OWN
 * Algorand wallet, leaving 22 of 20,049 main.devices docs with
 *   address === reward_wallet === device_algo_address
 * Such a doc resolves to no owner: pages/devices.tsx lists by {address: session wallet},
 * so the rightful owner cannot see it, and both registration routes refused to rebind it.
 *
 * The carve-out that lets the owner recover it must NOT be satisfiable by miner-key
 * possession alone — install keys circulate in Discord support threads. The proof used
 * here is creds.hardware.address: the wallet that registered the key at install time,
 * which the clobber never touched. A clobbered device with no creds.hardware record is
 * therefore NOT self-rebindable (14 of the 22 measured 2026-09-22); those need support.
 *
 * RC1-FIX (r12, 2026-09-22): creds.hardware.address ON ITS OWN is self-mintable, so the
 * carve-out as first shipped (22001c0) was forgeable end to end:
 *   1. POST /api/devices/save-credentials { miner_key, credentials } — for a key with no
 *      install record this upserts { miner_key, address: <session wallet> } into
 *      creds.hardware with no device-ownership check whatsoever;
 *   2. POST /api/registrations/register { miner_key } — the record minted in step 1 now
 *      "proves" the attacker installed the device, and the rebind hands it over.
 * Two independent changes close it:
 *   (a) the install record must PRE-DATE the carve-out. The only clock these docs carry is
 *       the _id ObjectId timestamp (Phase 1: the docs hold just _id/miner_key/address, plus
 *       credentials on some), and it is generated by the server on insert — no dashboard
 *       route can backdate it, because none of them supplies _id. Measured on ARES00
 *       2026-09-22: all 8 install records belonging to the 22 clobbered devices were created
 *       2026-06-23 .. 2026-07-11, i.e. every legitimate proof pre-dates the cutoff by months,
 *       while anything an attacker mints from now on is stamped now.
 *   (b) pages/api/devices/save-credentials.ts now refuses to write creds.hardware.address
 *       for a miner key whose main.devices doc is bound to a different wallet, so neither a
 *       fresh record nor an existing address-less one (48 of 7,556) can be pointed at an
 *       attacker in the first place.
 * (a) alone would still accept an old address-less record that (b) refuses to fill in; (b)
 * alone would still accept a record minted before this deploy. Both are required.
 */

const CREDS_DB_NAME = process.env.MONGO_CREDS_DB ?? 'creds';
const CREDS_HARDWARE_COLLECTION = process.env.MONGO_CREDS_COLLECTION ?? 'hardware';
const FEM_KEY_PATTERN = /^FEM-[A-Za-z0-9]{32}$/;

/**
 * Install records created at or after this instant are not accepted as ownership proof.
 * It is the day the rebind carve-out shipped (22001c0, 2026-09-22 17:25 -0500): every
 * pre-existing record pre-dates it, and nothing written after it can be trusted, because
 * before that commit no route had any reason to fabricate one.
 */
export const REBIND_PROOF_CUTOFF = new Date('2026-09-22T00:00:00.000Z');

const trimmed = (value: unknown): string =>
  typeof value === 'string' ? value.trim() : '';

/**
 * The two fields the clobber test reads. Callers pass `unknown` shapes (a Mongo
 * WithId<Document> from one route, a typed Device from another), so the narrowing happens
 * here rather than forcing a cast at every call site.
 */
type RebindCandidate = {
  address?: unknown;
  device_algo_address?: unknown;
};

/** True when the doc's bound wallet IS the device's own wallet (the July clobber state). */
export function isDeviceWalletClobber(device: unknown): boolean {
  if (!device || typeof device !== 'object') return false;
  const doc = device as RebindCandidate;
  const boundAddress = trimmed(doc.address);
  const deviceWallet = trimmed(doc.device_algo_address);
  return boundAddress.length > 0 && boundAddress === deviceWallet;
}

/** An install record's claimed owner plus the server clock that stamped the record. */
export type CredsHardwareProof = {
  address: string;
  /** ObjectId generation time, or null when the record carries no usable _id. */
  createdAt: Date | null;
};

/** The ObjectId's embedded creation time, defensively: any other _id shape proves nothing. */
function objectIdCreatedAt(id: unknown): Date | null {
  const getTimestamp = (id as { getTimestamp?: () => Date } | null | undefined)?.getTimestamp;
  if (typeof getTimestamp !== 'function') return null;
  try {
    const at = getTimestamp.call(id);
    return at instanceof Date && !Number.isNaN(at.getTime()) ? at : null;
  } catch {
    return null;
  }
}

/**
 * The install record creds.hardware holds for this miner key, or null.
 * Projects ONLY the address and the _id: creds.hardware also carries the device credential
 * blob, which nothing here may read.
 */
export async function credsHardwareOwnerProof(
  client: MongoClient,
  minerKey: string | null | undefined
): Promise<CredsHardwareProof | null> {
  const key = trimmed(minerKey);
  if (!key) return null;
  const collection = client.db(CREDS_DB_NAME).collection(CREDS_HARDWARE_COLLECTION);
  let record = await collection.findOne(
    { miner_key: key },
    { projection: { address: 1, _id: 1 } }
  );
  if (!record && FEM_KEY_PATTERN.test(key)) {
    // FEM 0.2.x clients generated lowercase-hex keys while the app displayed them
    // uppercased, mirroring the case-insensitive lookup both registration routes do.
    record = await collection.findOne(
      { miner_key: { $regex: '^' + key + '$', $options: 'i' } },
      { projection: { address: 1, _id: 1 } }
    );
  }
  const owner = trimmed(record?.address);
  if (!owner) return null;
  return { address: owner, createdAt: objectIdCreatedAt(record?._id) };
}

/**
 * The wallet creds.hardware recorded for this miner key at install time, or null.
 * NOT a gate on its own — the address is self-mintable; see mayRebindClobberedDevice.
 */
export async function credsHardwareOwnerAddress(
  client: MongoClient,
  minerKey: string | null | undefined
): Promise<string | null> {
  const proof = await credsHardwareOwnerProof(client, minerKey);
  return proof ? proof.address : null;
}

/**
 * The only gate that may relax an owner-mismatch refusal. All of:
 *   - the doc is in the clobber state,
 *   - the session wallet is the wallet named by the key's creds.hardware install record,
 *   - that record was created before REBIND_PROOF_CUTOFF (so it cannot have been minted for
 *     this purpose), and
 *   - the session wallet is not the device's own wallet.
 * Anything else is false.
 */
export async function mayRebindClobberedDevice(
  client: MongoClient,
  device: unknown,
  minerKey: string | null | undefined,
  sessionAddress: string | null | undefined
): Promise<boolean> {
  const wallet = trimmed(sessionAddress);
  if (!wallet) return false;
  if (!isDeviceWalletClobber(device)) return false;
  // Whoever holds the device's own keys is the device, not its owner.
  if (trimmed((device as RebindCandidate).device_algo_address) === wallet) return false;
  const proof = await credsHardwareOwnerProof(client, minerKey);
  if (!proof || proof.address !== wallet) return false;
  if (!proof.createdAt) return false;
  return proof.createdAt.getTime() < REBIND_PROOF_CUTOFF.getTime();
}

export const REBIND_NOTE =
  'RC1 self-service rebind: address/reward_wallet had been clobbered to the device wallet ' +
  'by the July premature binding; restored to the creds.hardware registration wallet.';

/** The metadata every rebind write records, so the pre-image stays recoverable. */
export function rebindMetadata(
  previousAddress: string,
  at: Date = new Date()
): { rebound_from: string; rebind_note: string; rebind_at: Date } {
  return {
    rebound_from: previousAddress,
    rebind_note: REBIND_NOTE,
    rebind_at: at,
  };
}
